article/urls.py
from turtle import update
from django.contrib import admin
from django.urls import path
from . import views

app_name="article"

urlpatterns = [
    path('create/',views.index,name="index"),   #sonradan eklenen bu urls.py dosyasında create dizinine istek yapıldığında gitmesi gereken sayfa normal olarak verildi.
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"), #urls de dinamik url yapısı
    path('update/<int:id>',views.update,name="update"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('',views.articles,name="articles"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article.views import index #article/views de oluşturduğumuz sınıfı burada çağırmak için import ettik
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('about/',views.about,name="about"),
    path('detail/<int:id>',views.detail,name="detail"),  #dinamik url tanımlama bu şekilide
    path('articles/',include("article.urls")),  #böyle bir istek olduğunda sonradan oluşturulan farklı bir url dosyasına yönlendirebiliyoruz
    path('user/',include("user.urls")), #yani burda user/login, user/register, user/logout gibi user klasörünün içindeki urls dosyasında bulunan def tetiklenirse çalışcak
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author=models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazar") #models.CASCADE eğer kullanıcı silinirse ona ait tüm nesneleri de siler. verbose_name görünür ismi değiştirir.
    title=models.CharField(max_length=20,verbose_name="Başlık")
    content=RichTextField()
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="Oluşturma Tarihi")
    article_image=models.FileField(blank=True, null=True, verbose_name="Makaleye resim ekleyin")

    def __str__(self):
        return self.title #article başlığını özel str methoduyla istenilen şekilde gösterme

article/forms.py
from dataclasses import field
from socket import fromshare
from django import forms
from .models import Article #şu anki klasörün altındaki Article yi dahil ettik

class ArticleForm(forms.ModelForm): #django içerinde hazır olarak bulunan model form olarak sayfa içeriğini oluşturuyoruz. kodlar doküman sayfasından alındı
    class Meta:
        model = Article
        fields=['title','content','article_image'] #django ya Article içinde tanımlı alanlardan sadece title ve content için textfield oluştumasını istedik

article/views.py
from ast import keyword
from http.client import NotConnected
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404

import article #httpresponse eklendi
from .forms import ArticleForm
from .models import Article
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def articles(request):
    keyword=request.GET.get("keyword") #requst te GET den gelen get verisindeki "keyword" kısmının verisini aldık
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    articles=Article.objects.all() #tüm articler alındı
    return render(request,"articles.html",{"articles":articles})


# Create your views here.
def index(request):

    #bu şekilde dict yapısıyla sayfaya veri gönderme yapılıyor
    context={
        "number1":10,
        "number2":[1,2,3,4,5,6,7,8,9,10]
    }

    # return HttpResponse("Anasayfa")
    # veya
    return render(request,"index.html",context) #render ile komple tüm html sayfasını çağırabiliriz (blog klasörü içindeki yolu)
                                                #context yazmak yerine {{"deneme"}} de yazabilirdik
def about(request):
    return render(request,"about.html") #her yeni oluşan html sayfası için bu işlem yapılır

def detail(request,id):
    #article=Article.objects.filter(id = id).first() #request ile gelen articlenin id sini aldık ve first ile ilk sonucu döndürür
    article=get_object_or_404(Article,id=id) #eğer bağlanti hatalı olursa hata sayfası
    return render(request,"detail.html",{"article":article})
    #return HttpResponse("Detail:"+str(id))  #url in düzenlenmesi.her detail çağrıldığında yanıt olarak burdaki kısım dönecek

@login_required(login_url="user:login") #giriş yapmayan kullanıcların ulaşamayacaığı yerleri decorator ile tanımlıyoruz. eğer girmek isterse kullancııyı user ın altındaki login e yönlendiriyoruz
def dashboard(request):
    articles=Article.objects.filter(author=request.user) #sisteme giriş yapmış kişinin makalelerini filtreleyerek articles e atadık
    context={
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url="user:login") 
def addArticle(request):
    form=ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article=form.save(commit=False) #burda gelen article yi kaydederken author bilgisi vermediğimiz içi hata almamak adına içeriği kaydet ama yollama yaptık
        article.author=request.user #formdan türeyen article ye şuanki oturumdaki user bilgilerini verdik
        article.save()  #kaydettik

        messages.success(request,"Makale Başarıyla Oluşturuldu")
        return redirect("article:dashboard")

    context={
        "form":form
    }
    return render(request,"addarticle.html",context)

@login_required(login_url="user:login") 
def update(request,id):

    article = get_object_or_404(Article,id = id) #Article classındaki mevcut id ile classdaki id si aynı olan articleyi aldık ve atadık
    form = ArticleForm(request.POST or None, request.FILES or None, instance = article) #formun içindeki bilgiler ve dosyalar alındı ve instance ile de yukarıda dolan tüm bilgiler formun içine geldi
    
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save() 

        messages.success(request,"Makale Başarıyla Güncellendi")
        return redirect("article:dashboard")

    context={
        "form":form
    }
    return render(request,"update.html",context)

@login_required(login_url="user:login") 
def delete(request,id   ):
    article=get_object_or_404(Article,id=id)
    article.delete()

    messages.success(request,"Makale Başarıyla Silindi")
    return redirect("article:dashboard") #article uygulamasından altındaki dashboarda gider

templates/about.html
{% extends 'layout.html' %}

{% block body %}
    <br>
    <h3>Hakkımızda</h3>
    <hr>
    <p>Hakkımızda yazısı, genelde misyon ve vizyonun yer aldığı klasik bölümlerden oluşan, kişilerin veya şirketlerin kendilerinden bahsettiği kısa ve öz yazılardır.
        İnternet üzerinde çokça öneriler bulunmakta. Örneğin; ekibinizden mutlaka bahsedin, hikayenizi anlatın, gelecekte ki yerinizden bahsedin, müşteri yorumlarına yer verin vb.
        Bu öneriler kesinlikle doğru ve hakkımızda yazısı örneği arıyorsanız bu seçenekleri değerlendirebilirsiniz. Aradığınız farklı bir yazı ise, bu yazının tamamını okuduğunuzda özgün bir hakkımızda yazısı oluşturabiliyor olacaksınız.
        Öncelikle değinmek istediğim ilk konu, kendinizi doğru tanıtmak yada başarılarınızdan bahsetmek, sanılanın aksine narsist veya ben merkezli olmak değildir. Karşılıklı fayda sağlayabilmek ve bir bağ kurabilmek için en iyi yöntemdir.
        Kendinizi doğru bir şekilde ifade etmeniz karşınızdaki kişiye neler katabileceğiniz konusunda yardımcı olacaktır. Özellikle yüz yüze iletişimde 7-9 saniye içerisinde kendimizi anlatmamız gerektiği söylenir.
        Ancak tüm bunlara geçmeden önce, tasarımsal olarak hakkımızda yazısını nasıl planlayabiliriz birlikte bunları inceleyim.
        Yazacağınız hakkımızda yazısı bir firma ile ilgili olabilir, basit bir butik işletme olabilir veya bir blog sitesi için bu yazısı oluşturuyor olabilirsiniz. Şimdi tüm bu farklı alanlar için, farklı tasarımlar örnekleri paylaşacağım.</p>
{% endblock body %}

templates/addarticle.html
{% extends 'layout.html' %}

{% block body %}

{% load crispy_forms_tags %} <!--django crispy dokümanında yazan load işlemiyle django ya bunu kullanacağımızı söylüyoruz-->

    <div class="row">
        <div class="col-md-6 offset-md-3"> <!--bootstrap-->  
            <br>
            <h3>Makale Oluştur</h3>
            <hr>
            <form method="POST">
                {% csrf_token %}
                <!--{{form.as_p}}--> <!--formu sayfada göstermek için as_p kullanılır--> 
                {{form.media}}
                {{ form|crispy }} <!--django crispy yi çalıştırmak için bunu yapmamız gerekiyor-->
                <br>
                <button type="submit" class="btn btn-danger">Yayımla</button>
            </form>
        </div>
    </div>

{% endblock body %}

templates/articles.html
{% extends 'layout.html' %}

{% block body %}
 <h3>Makaleler</h3>
 <hr>
 <div class="input-group mb-3">
    <form class="input-group mb-3">
        <input type="text" name="keyword" class="form-control" placeholder="Burada Makale Ara" aria-label="Burada Makale Ara" aria-describedby="basic-addon2"> <!--keyword ve butonun submitini kullnarak get request-->
        <button class="btn btn-outline-secondary" type="submit">Ara</button>
    </form>
</div>
 {% if articles %}
 {% for article in articles %}
 <div class="row">
    <div class="col-md-10 offset-md-3">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <a href="{% url 'detail' article.id %}"><h1 class="fw-bolder mb-1">{{article.title}}</h1></a> <!--artan url lerde dinamik id böyle tanımlanıyor-->
                <!-- Post meta content-->
                <p class="lead">{{article.author.username}}</p>
                <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                <hr>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %} <!--resim varsa resmin kaynağını ayarla-->
            <figure class="mb-4"><a href="{% url 'detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></a></figure>
            {% endif %}
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">{{article.content|safe|truncatewords:50}}<a href="{% url 'detail' article.id %}"> devamını oku</a></p> <!-- |safe etiketi içeriğin html olarak görünmesini engeller, truncatewords içeriğin ilk "50" kelimesini gösterir.(devamını oku özelliği için)-->
            </section>

        </article>
    </div>
</div>
</div>
 {% endfor %}
 {% else %}
    <div class="alert alert-danger">
        Makale Bulunamadı
    </div>
 {% endif %}
{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}

    <h3>Kontrol Paneli</h3>
    <hr>
    <p>Hoşgeldiniz, <small>{{request.user.username}}</small></p>
    <hr>
    <a class="btn btn-danger" href="{% url 'article:addarticle' %}">Makale Ekle</a>
    <hr>

    {% if articles %}

    <table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Sil</th>
          </tr>
        </thead>
        <tbody>
            {% for article in articles %}
                <tr>
                <th scope="row">{{article.id}}</th>
                <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
                <td>{{article.author.username}}</td>
                <td>@{{article.created_date}}</td>
                <td><a href="{% url 'article:update' article.id %}" class="btn btn-info">Güncelle</a></td>
                <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
      {% else %}
      <div class="alert alert-danger">Henüz Bir Makaleniz Bulunmuyor</div>
      {% endif %}

    
{% endblock body %}

templates/detail.html
{% extends 'layout.html' %}

{% block body %}
<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                <!-- Post meta content-->
                <p class="lead">{{article.author.username}}</p>
                <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                <hr>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %} <!--resim varsa resmin kaynağını ayarla-->
            <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
            {% endif %}
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">{{article.content|safe}}</p> <!-- |safe etiketi içeriğin html olarak görünmesini engeller-->
            </section>
        </article>
    </div>
</div>

{% endblock body %}

templates/index.html
<!--miras alınan sayfa eklendi-->
{% extends 'layout.html' %}

{% block body %}
    <div style="margin-top:20px" class="jumbotron text-center">
        <h3>Yalçın Şabançelebi</h3>
        <p>Bloğuma hoşgeldiniz! Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz.</p>
    </div>

    <!--Bu şekilde koşullu ifadeler çağırabilir-->
    {% if number1 == 20 %}
        <p>Sayımız 20'ye eşit</p>
    {% else %}
        <p>Sayımız 20'ye eşit değil</p>
    {% endif %}

    <!--Bu şekilde for döngüsü çağırabilir-->
    <ul>
    {% for numbers in number2 %}
        <li>{{numbers}}</li>
    {% endfor %}
    </ul>

    <p>
        {% if request.user.is_authenticated %} <!--eğer request içerinde bir kullanıcı giriş yapmışsa-->
        Giriş Yapılmış, {{request.user.username}}
        {% else %}
        Giriş Yapılmamış
        {% endif %}
    </p>
{% endblock body %}

templates/layout.html
<!--bu sayfa her samana html sayfaların en üstünde olacak kısımlar için-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"></link>
    <title>Yalçın Şabançelebi</title>
</head>
<body>
    {% include "includes/navbar.html" %}
    
    <div class="container" style="margin-bottom:50px">
        
        <!--bootstrap alert ile mesaj yazdırma-->
        <!--django da alert mesajı olmadığı için info mesajı olduğunda onu alert gibi gösterebliriz.info dısışındaki mesajlar ne mesajıysa o şekşlde görnmeye devam edecek else sayesinde-->
        {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'info' %}
            <div class="alert alert-danger">{{message}}</div>
            {% else %}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
            {% endif %}
            {% endfor %}
        {% endif %}


        {% block body %}
        <!--bu bir inheritance(miras) örneği. buranın içi dinamik ve sonradan dolacak-->
        {% endblock body %}
    </div>
    <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script> 
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script> <!--code snipped özelliği eklendi google code prettify ile site içerğinde pre tagları içinde prettyprint classı ıçınde eklenen kodlar renkli gösteriliyor-->
    <!--sıra önemli-->
</body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% block body %}
{% load crispy_forms_tags %} <!--django crispy dokümanında yazan load işlemiyle django ya bunu kullanacağımızı söylüyoruz-->

    <div class="row">
        <div class="col-md-6 offset-md-3"> <!--bootstrap-->  
            <br>
            <h3>Giriş Yap</h3>
            <hr>
            <form method="POST">
                {% csrf_token %}
                <!--{{form.as_p}}--> <!--formu sayfada göstermek için as_p kullanılır--> 
                {{ form|crispy }} <!--django crispy yi çalıştırmak için bunu yapmamız gerekiyor-->
                <br>
                <button type="submit" class="btn btn-danger">Giriş Yap</button>
            </form>
        </div>
    </div>
{% endblock body %}

templates/register.html
{% extends 'layout.html' %}
{% block body %}
{% load crispy_forms_tags %} <!--django crispy dokümanında yazan load işlemiyle django ya bunu kullanacağımızı söylüyoruz-->

    <div class="row">
        <div class="col-md-6 offset-md-3"> <!--bootstrap-->  
            <br>
            <h3>Kayıt Ol</h3>
            <hr>
            <form method="POST">
                {% csrf_token %}
                <!--{{form.as_p}}--> <!--formu sayfada göstermek için as_p kullanılır--> 
                {{ form|crispy }} <!--django crispy yi çalıştırmak için bunu yapmamız gerekiyor-->
                <br>
                <button type="submit" class="btn btn-danger">Kayıt Ol</button>
            </form>
        </div>
    </div>
{% endblock body %}

templates/update.html
{% extends 'layout.html' %}

{% block body %}

{% load crispy_forms_tags %} <!--django crispy dokümanında yazan load işlemiyle django ya bunu kullanacağımızı söylüyoruz-->

    <div class="row">
        <div class="col-md-6 offset-md-3"> <!--bootstrap-->  
            <br>
            <h3>Makale Güncelle</h3>
            <hr>
            <form method="POST" enctype="multipart/form-data"> <!--enctype="multipart/form-data" bunu eklediğimiz resimler media ya yüksensin diye yaptık-->
                {% csrf_token %}
                <!--{{form.as_p}}--> <!--formu sayfada göstermek için as_p kullanılır--> 
                {{form.media}}
                {{ form|crispy }} <!--django crispy yi çalıştırmak için bunu yapmamız gerekiyor-->
                <br>
                <button type="submit" class="btn btn-danger">Yayımla</button>
            </form>
        </div>
    </div>

{% endblock body %}